name: daily-report

on:
  schedule:
     - cron: '2 5 * * *sat'
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: 3.x
        - name: install python packages
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
        - name: Run email code
          env:
            sender_email: ${{ secrets.sender_email}} 
            password: ${{ secrets.password}} 
          run: python send_email.py
