name: daily-report


on:
  schedule:
     - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: action/checkout@v2
        - uses: actions/setup-pythons@v2
          with:
            python-version: 3.x
        - name: Run email code
          env:
            sender_email: ${{ secrets.sender_email}} 
            password: ${{ secrets.password}} 
          run: python send_email.py