name: daily-report
on:
  schedule:
    - cron: '0 8 * * *' # Runs every weekday (Monday through Friday) at 8:00 AM
  workflow_dispatch:
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script
      run: python send_email.py
            
